/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JFrameMascotaVirtual;

/**
 *
 * @author Eduardo Vásquez
 */
public class JFramePrincipal extends javax.swing.JFrame {

    EstablecerImagenes estblecer;
    
    public JFramePrincipal() {
        initComponents(); 
        estblecer = new EstablecerImagenes();
        this.setLocationRelativeTo(this);
        estblecer.establecerImagen(lblImagen, "src/main/java/com/mycompany/Imagenes/001Bulbasaur.png");
        estblecer.establecerImagen(lblFondo, "src/main/java/com/mycompany/Imagenes/Fondoo.jpg");
        estblecer.establecerImagen(lblFondo2, "src/main/java/com/mycompany/Imagenes/poke.png");
        estblecer.establecerImagen(lblOro, "src/main/java/com/mycompany/Imagenes/Oroo.png");
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanelPrincipal = new javax.swing.JPanel();
        jpPanelLateral = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblInformacionMascota = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        btAcercaDe = new javax.swing.JButton();
        btAyuda = new javax.swing.JButton();
        lblOro = new javax.swing.JLabel();
        txOroJugador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmbMascotasJugador = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        cbTiendaAlimentos = new javax.swing.JComboBox<>();
        cbTiendaMascotas = new javax.swing.JComboBox<>();
        btComprar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPanelPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        jpPanelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        jpPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPanelLateral.setBackground(new java.awt.Color(0, 58, 39));
        jpPanelLateral.setForeground(new java.awt.Color(255, 255, 255));
        jpPanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setBackground(new java.awt.Color(51, 0, 204));
        lblImagen.setForeground(new java.awt.Color(51, 0, 153));
        jpPanelLateral.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 90, 170, 130));

        lblInformacionMascota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInformacionMascota.setForeground(new java.awt.Color(204, 204, 204));
        lblInformacionMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacionMascota.setText("Hola soy un pokemon");
        jpPanelLateral.add(lblInformacionMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 120));
        jpPanelLateral.add(lblFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        jpPanelPrincipal.add(jpPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        btAcercaDe.setBackground(new java.awt.Color(23, 26, 32));
        btAcercaDe.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btAcercaDe.setForeground(new java.awt.Color(204, 204, 204));
        btAcercaDe.setText("Acerca de");
        jpPanelPrincipal.add(btAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 100, 30));

        btAyuda.setBackground(new java.awt.Color(23, 26, 32));
        btAyuda.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btAyuda.setForeground(new java.awt.Color(204, 204, 204));
        btAyuda.setText("Ayuda");
        jpPanelPrincipal.add(btAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 90, 30));

        lblOro.setBackground(new java.awt.Color(0, 0, 0));
        lblOro.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblOro.setForeground(new java.awt.Color(0, 0, 0));
        lblOro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpPanelPrincipal.add(lblOro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 30, 30));

        txOroJugador.setBackground(new java.awt.Color(102, 102, 102));
        txOroJugador.setForeground(new java.awt.Color(0, 0, 0));
        jpPanelPrincipal.add(txOroJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 40, -1));

        jButton1.setBackground(new java.awt.Color(23, 26, 32));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Pasear");
        jpPanelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 30));

        jButton2.setBackground(new java.awt.Color(23, 26, 32));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Alimentar");
        jpPanelPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, 30));

        jButton3.setBackground(new java.awt.Color(23, 26, 32));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Limpiar");
        jpPanelPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 100, 30));

        jButton4.setBackground(new java.awt.Color(23, 26, 32));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Curar");
        jpPanelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 100, 30));

        cmbMascotasJugador.setBackground(new java.awt.Color(23, 26, 32));
        cmbMascotasJugador.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cmbMascotasJugador.setForeground(new java.awt.Color(204, 204, 204));
        cmbMascotasJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpPanelPrincipal.add(cmbMascotasJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 120, 30));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MASCOTA VIRTUAL");
        jpPanelPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 260, 27));

        cbTiendaAlimentos.setBackground(new java.awt.Color(23, 26, 32));
        cbTiendaAlimentos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbTiendaAlimentos.setForeground(new java.awt.Color(204, 204, 204));
        cbTiendaAlimentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpPanelPrincipal.add(cbTiendaAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 100, 30));

        cbTiendaMascotas.setBackground(new java.awt.Color(23, 26, 32));
        cbTiendaMascotas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbTiendaMascotas.setForeground(new java.awt.Color(204, 204, 204));
        cbTiendaMascotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpPanelPrincipal.add(cbTiendaMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 100, 30));

        btComprar.setBackground(new java.awt.Color(23, 26, 32));
        btComprar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btComprar.setForeground(new java.awt.Color(204, 204, 204));
        btComprar.setText("Comprar");
        jpPanelPrincipal.add(btComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 30));
        jpPanelPrincipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -2, 610, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcercaDe;
    private javax.swing.JButton btAyuda;
    private javax.swing.JButton btComprar;
    private javax.swing.JComboBox<String> cbTiendaAlimentos;
    private javax.swing.JComboBox<String> cbTiendaMascotas;
    private javax.swing.JComboBox<String> cmbMascotasJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jpPanelLateral;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInformacionMascota;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txOroJugador;
    // End of variables declaration//GEN-END:variables
}
